### PR TITLE
Maintenance update min python versions and add testing for newer versions

### PR DESCRIPTION
**Pull request by samaloney**
* Major version support [NEP29](ttps://numpy.org/neps/nep-0029-deprecation_policy.htm)
   * python version min version now 3.9, 3.10, 3.11. *3.12*
* Temporarily disable code coverage on macOS CI as not working

### CODE REVIEW

**Comment by hayesla** [comment]
do you want to have this rename as part of this PR aswell or keep it separate to #114 or what order do you want?

**Comment by samaloney** [comment]
I'd planned to rebase this once #114 is merged

**Comment by samaloney** [comment]
All green - that was a bit of a journey, after #114 is merged and I rebase the changelog number problem should go away 🤞

**Review by KriSun95 — APPROVED** [review]

**Review by DanRyanIrish — APPROVED** [review]
lgtm!

**Pull request merged**
