### PR TITLE
Refactor redundant legacy

### PR DESCRIPTION
**Pull request by samaloney**
Remove redundant 'legacy' in module from `~sunkit_spex.legacy.fitting_legacy` to `sunkit_spex.legacy.fitting`.

### CODE REVIEW

**Comment by samaloney** [comment]
Note I haven't update the notebooks as they will be removed in #153

**Review by KriSun95 — APPROVED** [review]
The name change looks good to me!

**Comment by samaloney** [comment]
Reviews please

**Review by nabobalis — APPROVED** [review]

**Comment by nabobalis** [comment]
Why was it called legacy originally?

**Comment by samaloney** [comment]
Needed a way to delineate older code which won't be updated and will eventually be removed from what we are now trying to do

**Review by DanRyanIrish — APPROVED** [review]

**Pull request merged**
